const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const buildPrompt = (resumeText, jobDescription) => {
  // Truncate resume to ~3000 characters to control token cost
  const truncated = resumeText.slice(0, 3000);

  if (jobDescription && jobDescription.trim().length > 0) {
    const truncatedJd = jobDescription.slice(0, 3000);
    return `
You are a professional ATS system and expert technical recruiter.
Analyze the resume below strictly against the provided Job Description (JD).
Do not include any explanation, markdown, or text outside the JSON.

⚠️ IMPORTANT: Your analysis must be highly specific to the JD.

Job Description:
"""
${truncatedJd}
"""

Resume text:
"""
${truncated}
"""

Respond with exactly this JSON structure:
{
  "atsScore": <number between 0 and 100 representing the match percentage against the JD>,
  "atsScoreNote": "ATS match analysis generated by comparing your resume against the provided job description.",
  "matchedSkills": [<list of JD required/preferred skills found in the resume>],
  "missingSkills": [<list of JD required/preferred skills NOT found in the resume>],
  "experienceSummary": "<2-3 sentence analysis of how their experience aligns with the JD requirements>",
  "strengths": [<list of 3 specific resume strengths matching the JD>],
  "improvements": [<list of 3 personalized optimization suggestions for this specific JD>],
  "careerSuggestions": [<list of 1-3 job titles from the JD or highly related roles>],
  "overallFeedback": "<one honest paragraph summarizing their hiring fit for this specific JD>"
}
`;
  } else {
    return `
You are a professional resume analyst and career coach.

Analyze the resume below and respond with ONLY a valid JSON object.
Do not include any explanation, markdown, or text outside the JSON.

Resume text:
"""
${truncated}
"""

Respond with exactly this JSON structure:
{
  "atsScore": <number between 0 and 100 representing general resume quality>,
  "atsScoreNote": "General ATS-style resume evaluation based on resume quality, formatting, and keyword relevance.",
  "matchedSkills": [<list of skills found in the resume>],
  "missingSkills": [<list of commonly expected skills not found>],
  "experienceSummary": "<2-3 sentence summary of candidate experience>",
  "strengths": [<list of 3 resume strengths>],
  "improvements": [<list of 3 specific actionable improvements or missing common resume sections>],
  "careerSuggestions": [<list of 3 job titles this resume is suited for>],
  "overallFeedback": "<one honest paragraph of overall assessment>"
}
`;
  }
};

const validateAnalysis = (parsed) => {
  // These fields MUST exist — if any are missing, Gemini hallucinated a wrong structure
  const required = [
    "atsScore",
    "matchedSkills",
    "missingSkills",
    "strengths",
    "improvements",
    "careerSuggestions",
    "overallFeedback",
  ];

  for (const field of required) {
    if (parsed[field] === undefined) {
      throw new Error(`AI response missing required field: ${field}`);
    }
  }

  // Enforce types — Gemini sometimes returns score as a string
  if (typeof parsed.atsScore !== "number") {
    parsed.atsScore = parseInt(parsed.atsScore, 10);
  }

  // Clamp score between 0-100
  parsed.atsScore = Math.min(100, Math.max(0, parsed.atsScore));

  return parsed;
};

const analyzeResume = async (resumeText, jobDescription) => {
  // Prompt injection guard — if someone writes "ignore above instructions" in their resume
  const suspiciousPatterns = [
    /ignore (above|previous|all) instructions/i,
    /you are now/i,
    /disregard/i,
    /system prompt/i,
  ];

  const isSuspicious = suspiciousPatterns.some((pattern) =>
    pattern.test(resumeText),
  );

  if (isSuspicious) {
    throw new Error("Resume content contains invalid patterns");
  }

  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
  // Using flash not pro — cheaper, faster, sufficient for this task

  const prompt = buildPrompt(resumeText, jobDescription);

  const result = await model.generateContent(prompt);
  const rawText = result.response.text();

  // Gemini sometimes wraps JSON in markdown code blocks — strip them
  const cleaned = rawText
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();

  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    throw new Error("AI returned invalid JSON. Please try again.");
  }

  const validated = validateAnalysis(parsed);
  return validated;
};

module.exports = { analyzeResume };
